import type { BoardData } from '@/types/board.types';

export const mockBoardData: BoardData = {
    metadata: {
        generated_at: '2026-02-19T00:00:00Z',
        atomic_stories_version: 'v1.4.0',
        progress_version: 'v1.3.0',
        total_stories: 5,
        overall_completion_pct: 60,
    },
    stories: [
        {
            id: '001',
            title: 'Project Setup Command',
            description: 'Setup the project scaffolding',
            status: 'completed',
            effort: 3,
            priority: 'high',
            version: 'v1.0.0',
            category: 'MVP',
            dependencies: [],
            uacs: [
                { tag: 'CLI', description: 'Creates project structure', status: 'completed' },
                { tag: 'CLI', description: 'Generates templates', status: 'completed' },
            ],
            notes: 'Foundation story',
        },
        {
            id: '002',
            title: 'Review Command',
            description: 'Reverse-engineer documentation',
            status: 'completed',
            effort: 8,
            priority: 'high',
            version: 'v1.0.0',
            category: 'MVP',
            dependencies: [],
            uacs: [],
            notes: '',
        },
        {
            id: '101',
            title: 'Build Frontend Command',
            description: 'Scaffold frontend implementation',
            status: 'in_progress',
            effort: 13,
            priority: 'high',
            version: 'v1.1.0',
            category: 'Code Generation',
            dependencies: ['001'],
            uacs: [
                { tag: 'FE', description: 'Generates React components', status: 'completed' },
                { tag: 'FE', description: 'Creates test files', status: 'pending' },
                { tag: 'CLI', description: 'Reads documentation context', status: 'completed' },
            ],
            notes: '',
        },
        {
            id: '310',
            title: 'Learning Documentation',
            description: 'Capture and document learnings',
            status: 'pending',
            effort: 13,
            priority: 'high',
            version: 'v1.4.0',
            category: 'Knowledge Management',
            dependencies: ['001', '003'],
            uacs: [
                { tag: 'CLI', description: 'Command accepts learning description', status: 'pending' },
                { tag: 'CLI', description: 'Creates learning document', status: 'pending' },
            ],
            notes: '',
        },
        {
            id: '311',
            title: 'Code Review Command',
            description: 'Systematic code reviews',
            status: 'blocked',
            effort: 21,
            priority: 'high',
            version: 'v1.4.0',
            category: 'Quality Assurance',
            dependencies: ['001', '003', '004'],
            uacs: [
                { tag: 'CLI', description: 'Analyzes git diff', status: 'blocked' },
            ],
            notes: 'Requires git integration',
        },
    ],
    releases: [
        {
            version: 'v1.0.0',
            name: 'MVP',
            released_at: '2026-02-06',
            stories: ['001', '002'],
            key_achievements: [
                'Complete documentation system',
                'AI-assisted document elaboration',
            ],
        },
    ],
    metrics: {
        total_stories: 5,
        completed: 2,
        in_progress: 1,
        pending: 1,
        blocked: 1,
        completion_pct: 60,
        total_points_completed: 11,
        total_points_remaining: 47,
        points_by_version: {
            'v1.0.0': { completed: 11, total: 11, pct: 100 },
            'v1.1.0': { completed: 0, total: 13, pct: 0 },
            'v1.4.0': { completed: 0, total: 34, pct: 0 },
        },
        velocity_per_sprint: 10,
        estimated_remaining_sprints: 5,
        suggestions: [
            {
                type: 'available',
                priority: 'high',
                title: 'Story 310 is ready to start',
                detail: 'No unmet dependencies. High priority.',
            },
            {
                type: 'high-value',
                priority: 'high',
                title: 'Story 311 is high-value',
                detail: '21 story points, high priority.',
            },
        ],
    },
};
