/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#7b5800",
        "on-primary-container": "#96a9be",
        "on-secondary-fixed": "#271900",
        "on-background": "#191c1d",
        "on-primary-fixed-variant": "#36485b",
        "tertiary": "#3d1f00",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed": "#ffdcc1",
        "primary-fixed-dim": "#b5c8df",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#f7bd48",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadb",
        "on-surface-variant": "#43474c",
        "primary": "#162839",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "secondary-container": "#fdc34d",
        "error-container": "#ffdad6",
        "primary-fixed": "#d1e4fb",
        "tertiary-container": "#5b3205",
        "surface-container-high": "#e7e8e9",
        "surface": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#683d0f",
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "on-secondary-container": "#715000",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#b5c8df",
        "surface-tint": "#4e6073",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-tertiary-container": "#d69a65",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#2c3e50",
        "outline": "#74777d",
        "secondary-fixed": "#ffdea6",
        "tertiary-fixed-dim": "#f9ba82",
        "on-secondary-fixed-variant": "#5d4200",
        "on-tertiary-fixed": "#2e1500",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#091d2e",
        "outline-variant": "#c4c6cd"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
